#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Add ~/bin to $PATH.
path=(~/bin $path)

# Set env.
export EDITOR='vim'
export VISUAL=$EDITOR
export FZF_DEFAULT_COMMAND='fd --type f'

# Source direnv.
eval "$(direnv hook zsh)"

# Source fzf.
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source base16 colors.
BASE16_SHELL="$HOME/src/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

# Bind Ctrl-R to recursively search history.
bindkey "^R" history-incremental-search-backward

# Useful aliases.
alias gitwdiff='git diff --word-diff'
# alias ss='sshuttle -r sg1 0/0'

function gitignore() {
	if [ -z "$1" ]; then
		echo "Usage: gitignore <language>"
		echo "  Languages: https://github.com/github/gitignore"
	else
		curl -o .gitignore https://raw.githubusercontent.com/github/gitignore/master/$1.gitignore
	fi
}
